apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: saithota9/rabbitmq:1.0.0
        resources:
          requests:
            cpu: "15m"
            memory: "15Mi"
          limits:
            cpu: "75m"
            memory: "50Mi"
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10
        envFrom:
         - configMapRef:
             name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  lables:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672