apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_ROOT_PASSWORD: "RoboShop@1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mysql
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql
    spec:
      containers:
      - name: mysql
        image: saithota9/mysql:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "550Mi"
          limits:
            cpu: "300m"
            memory: "800Mi"
        startupProbe:
          tcpSocket:
            port: 3306
          failureThreshold: 120
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 120
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 120
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql 
spec:
  selector:
    project: roboshop
    tier: db
    component: mysql 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306